# Generated by Django 3.2.4 on 2021-06-25 17:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
        ('lecture', '0011_lecture_like_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('학습내용', '학습내용'), ('hi-sw 관련', 'hi-sw 관련'), ('진학상담', '진학상담'), ('기타', '기타')], default='기타', max_length=10)),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('question_reg_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='질문작성일')),
                ('answer', models.TextField(blank=True, null=True, verbose_name='질문에 대한 답변')),
                ('answer_reg_date', models.DateTimeField(blank=True, null=True, verbose_name='답변작성일')),
                ('answer_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.userprofile', verbose_name='질문 답변자')),
                ('lecture', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lecture.lecture')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='질문자')),
            ],
        ),
    ]
