# Generated by Django 3.2.4 on 2021-06-25 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0005_remove_lecture_like'),
        ('question', '0002_auto_20210625_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userquestion',
            name='lecture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lecture.lecture'),
        ),
    ]
