# Generated by Django 3.2.3 on 2021-06-20 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='app_end_date',
            field=models.DateTimeField(),
        ),
    ]
