# Generated by Django 3.2.3 on 2021-06-20 18:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lecture', '0003_alter_lecture_app_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='like',
            field=models.ManyToManyField(blank=True, related_name='lecture_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
