# Generated by Django 3.2.3 on 2021-06-20 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0004_lecture_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecture',
            name='like',
        ),
    ]
