# Generated by Django 3.2.4 on 2021-06-23 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('lecture', '0005_remove_lecture_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='enrol_students',
            field=models.ManyToManyField(related_name='enrol', to='accounts.UserProfile'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.userprofile'),
        ),
        migrations.AlterModelTable(
            name='lecture',
            table='Lecture',
        ),
    ]
