# Generated by Django 3.2.4 on 2021-06-23 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('lecture', '0006_auto_20210623_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='enrol_students',
            field=models.ManyToManyField(blank=True, related_name='enrol', to='accounts.UserProfile'),
        ),
    ]
