# Generated by Django 3.2.4 on 2021-06-23 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('lecture', '0008_alter_lecture_enrol_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='enrol_students',
            field=models.ManyToManyField(blank=True, related_name='enrol_student', to='accounts.UserProfile'),
        ),
    ]
