# Generated by Django 3.2.4 on 2021-06-24 00:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lecture', '0009_alter_lecture_enrol_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='enrol_students',
            field=models.ManyToManyField(blank=True, related_name='enrol', to=settings.AUTH_USER_MODEL),
        ),
    ]
