# Generated by Django 3.2.4 on 2021-06-26 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0011_lecture_like_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='lec_time',
            field=models.ImageField(default=0, upload_to=''),
        ),
    ]
