# Generated by Django 3.2.4 on 2021-06-26 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0011_lecture_like_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='lec_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lecture',
            name='webex_address',
            field=models.CharField(default='#', max_length=50),
        ),
    ]
