# Generated by Django 3.2.4 on 2021-06-26 09:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lecture', '0012_auto_20210626_0045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='like_users',
            field=models.ManyToManyField(blank=True, related_name='like_lectures', to=settings.AUTH_USER_MODEL),
        ),
    ]
