# Generated by Django 3.2.4 on 2021-06-26 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0012_lecture_lec_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='lec_time',
            field=models.IntegerField(default=0),
        ),
    ]
