# Generated by Django 3.2.4 on 2021-06-26 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0014_alter_category_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='english_name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(default='', max_length=20),
        ),
    ]
