# Generated by Django 3.2.4 on 2021-06-26 17:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lecture', '0016_auto_20210626_1642'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecture',
            name='host',
        ),
        migrations.AddField(
            model_name='lecture',
            name='host',
            field=models.ManyToManyField(blank=True, related_name='host', to=settings.AUTH_USER_MODEL),
        ),
    ]
