# Generated by Django 3.2.4 on 2021-06-26 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userprofile_service_hour'),
        ('lecture', '0017_auto_20210626_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='host',
            field=models.ManyToManyField(blank=True, related_name='host', to='accounts.UserProfile'),
        ),
    ]
