# Generated by Django 3.2.4 on 2021-06-26 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0013_alter_lecture_lec_time'),
        ('lecture', '0018_alter_lecture_host'),
    ]

    operations = [
    ]
