# Generated by Django 3.2.4 on 2021-06-27 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0019_merge_20210626_2304'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='showmain_lecture',
            field=models.CharField(choices=[('인기강의', '인기강의'), ('일주일 내 시작될 강의', '일주일 내 시작될 강의')], default='일주일 내 시작될 강의', max_length=20),
        ),
    ]
