# Generated by Django 3.2.4 on 2021-06-26 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_userprofile_school_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='service_hour',
            field=models.ImageField(default=0, upload_to=''),
        ),
    ]
