# Generated by Django 3.2.4 on 2021-06-26 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userprofile_service_hour'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='webex',
            field=models.URLField(default='', max_length=100),
        ),
    ]
