# Generated by Django 3.2.4 on 2021-06-26 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_userprofile_webex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='service_hour',
            field=models.IntegerField(default=0),
        ),
    ]
