# Generated by Django 3.2.4 on 2021-06-26 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_userprofile_service_hour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='webex',
            field=models.CharField(default='', max_length=100),
        ),
    ]
