# Generated by Django 3.2.4 on 2021-06-26 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_userprofile_webex'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='webex',
        ),
    ]
