# Generated by Django 3.2.4 on 2021-06-26 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myPage', '0002_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='writer',
        ),
    ]
